#!/bin/sh

install_mac_os() {
    brew install vim ctags

    brew install python
    pip install pyflakes pylint pep8

    brew install node
    npm install jshint -g
    npm install jslint -g
}

install_debain() {
    sudo apt-get install -y clang cmake build-essential 2>> err.log

    # 解决Ubuntu 14.04编译YCM时找不到libclang.so的问题
    if [ ! -e /usr/lib/llvm-3.4/lib/libclang.so ]
    then
        sudo ln -sf /usr/lib/llvm-3.4/lib/libclang.so.1 /usr/lib/llvm-3.4/lib/libclang.so
    elif [ -L /usr/lib/llvm-3.4/lib/libclang.so ]
    then
        sudo unlink /usr/lib/llvm-3.4/lib/libclang.so
        sudo ln -sf /usr/lib/llvm-3.4/lib/libclang.so.1 /usr/lib/llvm-3.4/lib/libclang.so
    fi

    sudo apt-get install -y vim ctags 2>> err.log
    sudo apt-get install -y python-dev python-setuptools 2>> err.log
    sudo easy_install pip
    sudo pip install pyflakes pylint pep8

    sudo apt-get install -y nodejs-legacy npm 2>> err.log
    sudo npm install jslint -g
    sudo npm install jshint -g
}

install_fedora() {
    sudo yum install vim -y
    sudo yum install python-devel.x86_64
    sudo yum groupinstall 'Development Tools'
}


system_shell=$SHELL
export SHELL="/bin/sh"

if [ `which brew` ]
then
    install_mac_os
elif [ `which apt-get` ]
then
    install_debain
elif [ `which yum` ]
then
    install_fedora
fi

export SHELL=$system_shell
